Fix heating state reporting
This was seen in the log:

[zigpy.util] Error calling listener <bound method ME167Thermostat.hass_climate_state_change
 of <zhaquirks.tuya.ts0601_trv_me167.ME167Thermostat object at 0x7f7b8126ebe0>>
 with args (1,):
 TypeError("hass_climate_state_change() missing 1 required positional argument: 'value'")